# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b76a62fbebb9f543f3f6f3f5d805f8699aceb03c2f784ad5a85758c534016b13f2cb73f81bf01cc8e7e17fc7f31be5f56c77c703aaa9cf189cf2c7ad1c44bf4

test:
  secret_key_base: 58f32b7163c8899af9eb246e29d142daabcb3bef6a4c9fc1b8f506c40ec5597c289087e8d5e217032309fbc8ecab6ddbba2200206bcc0bbb5143b078fc083d37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
